name: xgo

concurrency:
  group: xgo-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build artifacts
        uses: docker/bake-action@v2
        with:
          targets: artifact-all
      -
        name: Release
        uses: docker/bake-action@v2
        with:
          targets: release
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xgo
          path: ./release/*
          if-no-files-found: error
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: |
            release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
